image: openjdk:17-jdk

before_script:
  - chmod +x gradlew
  - rm -rf build/libs

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew build -S
  artifacts:
    paths:
      - build/libs/*.jar
